apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true

    jsonData:
      server: "clickhouse"
      protocol: "http"
      port: "8123"
      username: "otel"
      defaultDatabase: "default"
      timeout: "60"
      dialTimeout: "10"

    secureJsonData:
      password: "otelpass"

    editable: true
